name: ConsulatCore
version: ${version}
author: Amisoz
main: fr.amisoz.consulatcore.ConsulatCore
api-version: 1.14
commands:
    rank:
    sanction:
    report:
    annonce:
    unmute:
    unban:
    staff:
    tpmod:
    help:
    mp:
    spawn:
    advert:
    kick:
    sc:
    chat:
    gm:
    back:
    hub:
    stafflist:
    news:
    r:
    seen:
    invsee: