name: ConsulatCore
version: ${version}
author: Amisoz
main: fr.amisoz.consulatcore.ConsulatCore
softdepend: [ConsulatAPI]
api-version: 1.14
commands:
    rank:
    sanction:
    report:
    annonce:
    unmute:
    unban:
    staff:
    tpmod:
    help:
    msg:
    spawn:
    advert:
    kick:
    sc:
    chat:
    gm:
    back:
    hub:
    stafflist:
    news:
    r:
    seen:
    invsee:
    boutique:
    perso:
    site:
    discord:
    duel: