name: ConsulatCore
version: ${version}
authors: [Amisoz, adracode]
main: fr.amisoz.consulatcore.ConsulatCore
depend: [ConsulatAPI]
api-version: 1.14
commands:
    rank:
    sanction:
    report:
    annonce:
    unmute:
    unban:
    staff:
    tpmod:
    help:
    msg:
        aliases: [mp]
    spawn:
    advert:
    kick:
    sc:
    chat:
    gm:
    back:
    hub:
    stafflist:
    news:
    r:
    seen:
    invsee:
    boutique:
    perso:
    site:
    discord:
    duel:
    ec:
    up:
    fly:
    top:
    sp:
    home:
    delhome:
    sethome:
    access:
    claim:
    unclaim:
    baltop:
    money:
    pay:
    tpa:
    shop:
    socialspy: